// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// loglIBBCpp
double loglIBBCpp(NumericVector p, IntegerVector ct, NumericVector sf, IntegerVector y, NumericVector z, NumericMatrix DO_par);
RcppExport SEXP _DECENT_loglIBBCpp(SEXP pSEXP, SEXP ctSEXP, SEXP sfSEXP, SEXP ySEXP, SEXP zSEXP, SEXP DO_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sf(sfSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DO_par(DO_parSEXP);
    rcpp_result_gen = Rcpp::wrap(loglIBBCpp(p, ct, sf, y, z, DO_par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DECENT_loglIBBCpp", (DL_FUNC) &_DECENT_loglIBBCpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DECENT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
