// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// optimLRTCpp
Rcpp::List optimLRTCpp(const NumericVector p, const IntegerVector ct, const NumericVector sf, const IntegerVector y, const NumericVector z, const NumericMatrix DO_par);
RcppExport SEXP _DECENT_optimLRTCpp(SEXP pSEXP, SEXP ctSEXP, SEXP sfSEXP, SEXP ySEXP, SEXP zSEXP, SEXP DO_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sf(sfSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type DO_par(DO_parSEXP);
    rcpp_result_gen = Rcpp::wrap(optimLRTCpp(p, ct, sf, y, z, DO_par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DECENT_optimLRTCpp", (DL_FUNC) &_DECENT_optimLRTCpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DECENT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
