# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(p, ct, sf, y, z, DO_par) {
    .Call('_DECENT_test', PACKAGE = 'DECENT', p, ct, sf, y, z, DO_par)
}

loglIBBCpp <- function(p, ct, sf, y, z, DO_par) {
    .Call('_DECENT_loglIBBCpp', PACKAGE = 'DECENT', p, ct, sf, y, z, DO_par)
}

